<?php

use Illuminate\Foundation\Inspiring;
use Illuminate\Support\Facades\Artisan;

Artisan::command('inspire', function () {
    $this->comment(Inspiring::quote());
})->purpose('Display an inspiring quote');

// Counter-closing reports are now generated by ShiftController::closeCounter()
// at the moment a counter is actually closed (counter-wise, session-scoped),
// not on a nightly/calendar-day schedule. The old `report:daily` cron used
// whereDate('end_time', yesterday), which produced wrong (often zero) totals
// for sessions that ran past midnight or spanned more than a day, and it
// reported per-shift instead of per-counter-session. `report:daily` remains
// available to run manually as a backfill/repair tool, but is no longer
// scheduled automatically.